version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: "composer"
    directory: "/"
    versioning-strategy: increase-if-necessary
    schedule:
      interval: "weekly"
